---

- hosts: all
  gather_facts: False 

  vars_files:
    - vars.yml

  tasks:

    - name: Update configuration
      git: repo=https://github.com/klen/.home dest={{inventory_dir}}

    - name: Setup bash - pt. 1
      file: state=link dest=~{{home_user}}/.{{item}} src={{inventory_dir}}/cfg/bash/{{item}}
      with_items:
      - bashrc
      - bash_aliases
      - bash_profile

    - name: Setup bash - pt. 2
      file: state=link dest=~{{home_user}}/bin src={{inventory_dir}}/bin

    - name: Setup utils
      file: state=link dest=~{{home_user}}/.{{item}} src={{inventory_dir}}/cfg/{{item}}
      with_items:
      - ctags
      - gitconfig
      - hgrc
      - pip
      - pylintrc
      - screenrc

    - name: Setup smartcd - pt. 1
      file: state=directory path=~{{home_user}}/.smartcd/virtualenvs

    - name: Setup smartcd - pt. 2
      file: state=link dest=~{{home_user}}/.smartcd/templates/{{item}} src={{inventory_dir}}/cfg/smartcd/templates/{{item}} force=yes
      with_items:
      - vagrant
      - virtualenv

    - name: Ensure VIM settings is updated
      git: repo=https://github.com/klen/.vim dest=~{{home_user}}/.vim
    # - name: Setup cheat
    # - name: Setup gnupg
