---

- hosts: all
  tasks:
  - homebrew: name=caskroom/cask/brew-cask
  - homebrew_cask: name={{item}}
    with_items:
    - 1password
    - alfred
    - calibre
    - ccleaner
    - docker
    - dropbox
    - flux
    - google-chrome
    - google-drive
    - google-play-music-desktop-player
    - hyperdock
    - istat-menus
    - iterm2
    - skype
    - slack
    - telegram
    - transmission
    - tunnelblick
    - vlc
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
