---

- hosts: all

  vars_files:
  - vars.yml

  tasks:

  - include: install.yum.yml
    when: ansible_os_family == "RedHat"
    become: yes

  - include: install.deb.yml
    when: ansible_os_family == "Debian"
    become: yes

  - include: install.osx.yml
    when: ansible_os_family == "Darwin"
    become: yes

  - name: Setup bash - pt. 1
    file: state=link dest=~{{home_user}}/.{{item}} src={{inventory_dir}}/cfg/bash/{{item}} force=yes owner={{home_user}}
    with_items:
    - bashrc
    - bash_aliases
    - bash_profile

  - name: Setup bash - pt. 2
    file: state=link dest=~{{home_user}}/bin src={{inventory_dir}}/bin force=yes owner={{home_user}}

  - name: Setup utils
    file: state=link dest=~{{home_user}}/.{{item}} src={{inventory_dir}}/cfg/{{item}} force=yes owner={{home_user}}
    with_items:
    - ctags
    - gitconfig
    - hgrc
    - pylintrc
    - screenrc
    - vimrc

  - name: Setup pip - pt. 1
    file: state=directory dest=~{{home_user}}/.pip owner={{home_user}}

  - name: Setup pip - pt. 2
    file: state=link dest=~{{home_user}}/.pip/pip.conf src={{inventory_dir}}/cfg/pip/pip.conf force=yes owner={{home_user}}

  - name: Setup pip - pt. 3
    pip: name={{item}}
    become: yes
    with_items:
      - git-up
      - httpie
      - virtualenv

  - name: Setup smartcd - pt. 1
    file: state=directory path={{item}} owner={{home_user}}
    with_items:
    - "~{{home_user}}/.smartcd"
    - "~{{home_user}}/.smartcd/virtualenvs"
    - "~{{home_user}}/.smartcd/templates"

  - name: Setup smartcd - pt. 2
    file: state=link dest=~{{home_user}}/.smartcd/templates/{{item}} src={{inventory_dir}}/cfg/smartcd/templates/{{item}} force=yes owner={{home_user}}
    with_items:
    - vagrant
    - virtualenv

  - name: Setup cheat
    file: state=link dest=~{{home_user}}/.cheat src={{inventory_dir}}/lib/cheat/data force=yes owner={{home_user}}

  - name: Setup ssh - pt. 1
    file: state=directory dest=~{{home_user}}/.ssh owner={{home_user}}

  - name: Setup ssh - pt. 2
    lineinfile: >
      dest=~{{home_user}}/.ssh/authorized_keys
      line="{{item}}"
      create=yes
    with_items: "{{home_authorized_keys}}"

  - name: Setup ssh - pt. 3
    lineinfile: >
      dest=~{{home_user}}/.ssh/known_hosts
      line="{{item}}"
      create=yes
    with_items: "{{home_fingerprints}}"

  - name: Setup VIM
    git: repo=https://github.com/klen/.vim dest=~{{home_user}}/.vim depth=2
    become_user: "{{home_user}}"

  - file: state=directory owner={{home_user}} recurse=yes path=~{{home_user}}/.home

# vim:sw=2:ft=ansible
